version: "3.8"

services:

  php:
    image: php:7-4-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 index.php
    environment:
      docker: "true"
    ports:
    - 8080:8080
    volumes:
      - .:/var/www
    networks:
      - net

  composer:
    image: composer:latest
    working_dir: /var/www
    command: install
    volumes:
    - .:/var/www

  redis:
    image: redis:6.0.8-alpine
    networks:
      - net

networks:
  net:
    driver: bridge