version: "3.8"

services:

  php:
    image: php:7.4-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 index.php
    environment:
      docker: "true"
    ports:
    - 8080:8080
    volumes:
      - .:/var/www
    networks:
      net:
        ipv4_address: 192.168.0.2

  composer:
    image: library/composer:2.0.0-RC1
    working_dir: /var/www
    command: install
    volumes:
    - .:/var/www

  redis:
    image: redis:6.0.8-alpine
    networks:
      net:
        ipv4_address: 192.168.0.1

  ab:
    image: jordi/ab:latest
    command: -n 100 -c 10 http://192.168.0.2:8080/
    networks:
      net:
        ipv4_address: 192.168.0.4

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.3
