version: "3.8"

services:

  php:
    image: php:7-4-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 index.php
    environment:
      docker: "true"
    ports:
    - 8080:8080
    volumes:
      - .:/var/www

  composer:
    image: composer:latest
    working_dir: /var/www
    command: install
    volumes:
    - .:/var/www

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - 6379:6379